# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 00:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(default=b' ', max_length=30)),
                ('details', models.TextField(default=b' ')),
                ('rate', models.IntegerField(default=b' ')),
                ('itemimage', models.ImageField(default=b' ', upload_to=b'/home/sinwar/djcode/sni/sni/site_media/media/things/')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2016, 5, 28, 0, 17, 34, 341240))),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.TextField(default=b' ')),
                ('last_name', models.TextField(default=b' ')),
                ('image', models.ImageField(default=b' ', upload_to=b'/home/sinwar/djcode/sni/sni/site_media/media')),
                ('mobile', models.IntegerField(default=668)),
                ('address', models.TextField(default=b' ')),
                ('facebook', models.TextField(default=b' ')),
            ],
        ),
        migrations.AddField(
            model_name='addthing',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owneruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
