# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(default=b' '),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.TextField(default=b' '),
        ),
    ]
