# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addthing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 19, 22, 20, 57, 300853)),
        ),
    ]
