# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 23:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sni', '0002_addthing_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='newnotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(default=b' ', max_length=30)),
                ('message', models.TextField(default=b' ')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticesender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='addthing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 23, 24, 6, 334296)),
        ),
    ]
