# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0002_auto_20160504_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
    ]
