# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 16:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0002_auto_20160519_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addthing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 27, 16, 23, 58, 725695)),
        ),
        migrations.AlterField(
            model_name='addthing',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owneruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
