# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0003_auto_20160529_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='newnotice',
            name='type',
            field=models.CharField(default=b' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='addthing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 15, 24, 27, 201370)),
        ),
    ]
