# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0005_auto_20160510_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=b' ', upload_to=b''),
        ),
    ]
