# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0008_auto_20160511_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=b' ', upload_to=b'site_media/media/'),
        ),
    ]
