# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('sni', '0010_auto_20160511_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='addThing',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('itemname', models.CharField(default=b' ', max_length=30)),
                ('details', models.TextField(default=b' ')),
                ('rate', models.IntegerField(default=b' ')),
                ('itemimage', models.ImageField(default=b' ', upload_to=b'/home/sinwar/djcode/sni/sni/site_media/mediathings/')),
            ],
        ),
    ]
