# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0011_addthing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addthing',
            name='itemimage',
            field=models.ImageField(default=b' ', upload_to=b'/home/sinwar/djcode/sni/sni/site_media/media/things/'),
        ),
    ]
