# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0012_auto_20160516_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='addthing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 11, 58, 38, 498302)),
        ),
    ]
