# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 21:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0016_auto_20160516_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addthing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 21, 13, 3, 586124)),
        ),
        migrations.AlterField(
            model_name='addthing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
